-- quest_rewards: tasks(3)+quests(12)+saga(19)+side(25)+daily(10)
insert into public.quest_rewards (quest_id, reward) values ('task:t1', '{"crystals":3}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('task:t2', '{"crystals":2}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('task:t3', '{"crystals":4}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('quest:t1', '{"gold":3}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('quest:t2', '{"gold":2}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('quest:t3', '{"gold":4}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('quest:q_kill', '{"gold":680}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('quest:q_cap', '{"gold":880}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('quest:q_berry', '{"gold":460}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('quest:q_ep1', '{"gold":750}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('quest:q_kill2', '{"gold":900}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('quest:q_cap2', '{"gold":1200}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('quest:q_berry2', '{"gold":650}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('quest:q_ep2', '{"gold":1100}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('quest:q_vip', '{"gold":1850}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('saga:rir', '{"items":[{"itemId":"pokeball","qty":5}]}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('saga:boby2', '{"items":[{"itemId":"pokeball","qty":8}]}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('saga:boby3', '{"items":[{"itemId":"greatball","qty":3}]}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('saga:prometo', '{"items":[{"itemId":"pokeball","qty":5}]}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('saga:san1', '{"items":[{"itemId":"orb_xp_minor","qty":1}]}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('saga:san2', '{"items":[{"itemId":"orb_xp_minor","qty":1}]}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('saga:san3', '{"items":[{"itemId":"orb_team","qty":1}]}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('saga:sei', '{"items":[{"itemId":"orb_xp_minor","qty":1}]}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('saga:nani1', '{"items":[{"itemId":"fruta","qty":2}]}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('saga:nani2', '{"items":[{"itemId":"suco","qty":2}]}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('saga:nani3', '{"items":[{"itemId":"refeicao","qty":1}]}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('saga:nani4', '{"items":[{"itemId":"morango","qty":2}]}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('saga:payka2', '{"gold":800}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('saga:payka3', '{"gold":500}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('saga:jamais', '{"gold":1200}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('saga:pan1', '{"items":[{"itemId":"potion","qty":2}]}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('saga:pan2', '{"gold":300,"items":[{"itemId":"revive","qty":1}]}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('saga:pan3', '{"gold":500}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('saga:juntos', '{"items":[{"itemId":"potion","qty":3}]}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('side:boby_s1', '{"crystals":4,"items":[{"itemId":"pokeball","qty":3}]}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('side:boby_s2', '{"crystals":4,"items":[{"itemId":"greatball","qty":2}]}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('side:boby_s3', '{"crystals":5,"items":[{"itemId":"pokeball","qty":5}]}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('side:boby_s4', '{"crystals":5,"items":[{"itemId":"ultraball","qty":1}]}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('side:boby_s5', '{"crystals":5,"items":[{"itemId":"ultraball","qty":3}]}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('side:san_s1', '{"crystals":4,"items":[{"itemId":"orb_xp_minor","qty":1}]}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('side:san_s2', '{"crystals":4,"items":[{"itemId":"book_exp","qty":1}]}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('side:san_s3', '{"crystals":5,"items":[{"itemId":"orb_xp_minor","qty":1}]}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('side:san_s4', '{"crystals":5,"items":[{"itemId":"orb_xp_minor","qty":2}]}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('side:san_s5', '{"crystals":5,"items":[{"itemId":"orb_team","qty":1}]}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('side:nan_s1', '{"crystals":4,"items":[{"itemId":"fruta","qty":2}]}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('side:nan_s2', '{"crystals":4,"items":[{"itemId":"morango","qty":2}]}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('side:nan_s3', '{"crystals":5,"items":[{"itemId":"refeicao","qty":2}]}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('side:nan_s4', '{"crystals":5,"items":[{"itemId":"refeicao","qty":2}]}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('side:nan_s5', '{"crystals":5,"items":[{"itemId":"morango","qty":4}]}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('side:pay_s1', '{"crystals":4}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('side:pay_s2', '{"crystals":4}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('side:pay_s3', '{"crystals":5}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('side:pay_s4', '{"crystals":5}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('side:pay_s5', '{"crystals":5}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('side:pan_s1', '{"crystals":4,"items":[{"itemId":"potion","qty":2}]}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('side:pan_s2', '{"crystals":4,"items":[{"itemId":"revive","qty":2}]}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('side:pan_s3', '{"crystals":5}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('side:pan_s4', '{"crystals":5,"items":[{"itemId":"ultraball","qty":1}]}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('side:pan_s5', '{"crystals":5,"items":[{"itemId":"revive","qty":2}]}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('daily:1', '{"gold":500}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('daily:2', '{"gold":1000}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('daily:3', '{"gold":1500}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('daily:4', '{"gold":2000}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('daily:5', '{"gold":2500}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('daily:6', '{"gold":3000}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('daily:7', '{"gold":5000}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('daily:8', '{"gold":4000}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('daily:9', '{"gold":4500}') on conflict (quest_id) do update set reward = excluded.reward;
insert into public.quest_rewards (quest_id, reward) values ('daily:10', '{"gold":5000}') on conflict (quest_id) do update set reward = excluded.reward;
-- redeem_codes: 46
insert into public.redeem_codes (code, reward, max_uses) values ('BLACKMITIC01', '{"egg_black":1,"plus":1}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('BLACKMITIC02', '{"egg_black":1,"plus":1}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('BLACKMITIC03', '{"egg_black":1,"plus":1}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('BLACKMITIC04', '{"egg_black":1,"plus":1}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('BLACKMITIC05', '{"egg_black":1,"plus":1}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('BLACKMITIC06', '{"egg_black":1,"plus":1}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('BLACKMITIC07', '{"egg_black":1,"plus":1}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('BLACKMITIC08', '{"egg_black":1,"plus":1}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('BLACKMITIC09', '{"egg_black":1,"plus":1}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('BLACKMITIC10', '{"egg_black":1,"plus":1}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('BLACKPLUS6X01', '{"egg_black_ready":6}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('BLACKPLUS1X01', '{"egg_black_ready":1}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('BLACKPLUS6X02', '{"egg_black_ready":6}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('BLACKPLUS1X02', '{"egg_black_ready":1}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('BLACKPLUS6X03', '{"egg_black_ready":6}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('BLACKPLUS1X03', '{"egg_black_ready":1}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('BLACKPLUS6X04', '{"egg_black_ready":6}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('BLACKPLUS1X04', '{"egg_black_ready":1}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('BLACKPLUS6X05', '{"egg_black_ready":6}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('BLACKPLUS1X05', '{"egg_black_ready":1}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('CRYSTAL10K01', '{"crystals":10000}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('CRYSTAL50K01', '{"crystals":50000}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('CRYSTAL10K02', '{"crystals":10000}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('CRYSTAL50K02', '{"crystals":50000}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('CRYSTAL10K03', '{"crystals":10000}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('CRYSTAL50K03', '{"crystals":50000}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('CRYSTAL10K04', '{"crystals":10000}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('CRYSTAL50K04', '{"crystals":50000}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('CRYSTAL10K05', '{"crystals":10000}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('CRYSTAL50K05', '{"crystals":50000}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('CRYSTAL10K06', '{"crystals":10000}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('CRYSTAL50K06', '{"crystals":50000}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('CRYSTAL10K07', '{"crystals":10000}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('CRYSTAL50K07', '{"crystals":50000}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('CRYSTAL10K08', '{"crystals":10000}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('CRYSTAL50K08', '{"crystals":50000}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('CRYSTAL10K09', '{"crystals":10000}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('CRYSTAL50K09', '{"crystals":50000}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('CRYSTAL10K10', '{"crystals":10000}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('CRYSTAL50K10', '{"crystals":50000}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('EGGBOOST69', '{"esmeraldas":500,"items":[{"itemId":"egg_boost_69","qty":6},{"itemId":"stone_pack_all","qty":1}]}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('IDLM4L4USAFH', '{"egg_emerald":1}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('IDLMWZNHZFJT', '{"items":[{"itemId":"stone_grass","qty":50},{"itemId":"stone_fire","qty":50},{"itemId":"stone_water","qty":50},{"itemId":"stone_electric","qty":50},{"itemId":"stone_dark","qty":50},{"itemId":"stone_dragon","qty":50}]}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('IDLMZMMGAMDV', '{"crystals":300}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('IDLMGKPAHVTZ', '{"items":[{"itemId":"book_exp","qty":3},{"itemId":"orb_xp_minor","qty":3}]}', 1) on conflict (code) do update set reward = excluded.reward;
insert into public.redeem_codes (code, reward, max_uses) values ('IDLMZKPX2HW4', '{"gold":30000}', 1) on conflict (code) do update set reward = excluded.reward;
-- shop_offers: 21
insert into public.shop_offers (item_id, price_gold, price_crystal) values ('pokeball', 500, null) on conflict (item_id) do update set price_gold = excluded.price_gold, price_crystal = excluded.price_crystal;
insert into public.shop_offers (item_id, price_gold, price_crystal) values ('greatball', 5000, null) on conflict (item_id) do update set price_gold = excluded.price_gold, price_crystal = excluded.price_crystal;
insert into public.shop_offers (item_id, price_gold, price_crystal) values ('ultraball', null, 100) on conflict (item_id) do update set price_gold = excluded.price_gold, price_crystal = excluded.price_crystal;
insert into public.shop_offers (item_id, price_gold, price_crystal) values ('book_atk', null, 100) on conflict (item_id) do update set price_gold = excluded.price_gold, price_crystal = excluded.price_crystal;
insert into public.shop_offers (item_id, price_gold, price_crystal) values ('book_def', null, 100) on conflict (item_id) do update set price_gold = excluded.price_gold, price_crystal = excluded.price_crystal;
insert into public.shop_offers (item_id, price_gold, price_crystal) values ('book_exp', null, 30) on conflict (item_id) do update set price_gold = excluded.price_gold, price_crystal = excluded.price_crystal;
insert into public.shop_offers (item_id, price_gold, price_crystal) values ('maca', 200, null) on conflict (item_id) do update set price_gold = excluded.price_gold, price_crystal = excluded.price_crystal;
insert into public.shop_offers (item_id, price_gold, price_crystal) values ('laranja', 200, null) on conflict (item_id) do update set price_gold = excluded.price_gold, price_crystal = excluded.price_crystal;
insert into public.shop_offers (item_id, price_gold, price_crystal) values ('energetico', 900, null) on conflict (item_id) do update set price_gold = excluded.price_gold, price_crystal = excluded.price_crystal;
insert into public.shop_offers (item_id, price_gold, price_crystal) values ('potion', 250, null) on conflict (item_id) do update set price_gold = excluded.price_gold, price_crystal = excluded.price_crystal;
insert into public.shop_offers (item_id, price_gold, price_crystal) values ('revive', 400, null) on conflict (item_id) do update set price_gold = excluded.price_gold, price_crystal = excluded.price_crystal;
insert into public.shop_offers (item_id, price_gold, price_crystal) values ('antidoto', 150, null) on conflict (item_id) do update set price_gold = excluded.price_gold, price_crystal = excluded.price_crystal;
insert into public.shop_offers (item_id, price_gold, price_crystal) values ('orb_xp_minor', null, 100) on conflict (item_id) do update set price_gold = excluded.price_gold, price_crystal = excluded.price_crystal;
insert into public.shop_offers (item_id, price_gold, price_crystal) values ('orb_team', null, 2000) on conflict (item_id) do update set price_gold = excluded.price_gold, price_crystal = excluded.price_crystal;
insert into public.shop_offers (item_id, price_gold, price_crystal) values ('bolo_morango', 1200, null) on conflict (item_id) do update set price_gold = excluded.price_gold, price_crystal = excluded.price_crystal;
insert into public.shop_offers (item_id, price_gold, price_crystal) values ('refrigerante', 600, null) on conflict (item_id) do update set price_gold = excluded.price_gold, price_crystal = excluded.price_crystal;
insert into public.shop_offers (item_id, price_gold, price_crystal) values ('cafe', 500, null) on conflict (item_id) do update set price_gold = excluded.price_gold, price_crystal = excluded.price_crystal;
insert into public.shop_offers (item_id, price_gold, price_crystal) values ('picole', 300, null) on conflict (item_id) do update set price_gold = excluded.price_gold, price_crystal = excluded.price_crystal;
insert into public.shop_offers (item_id, price_gold, price_crystal) values ('cha_verde', 350, null) on conflict (item_id) do update set price_gold = excluded.price_gold, price_crystal = excluded.price_crystal;
insert into public.shop_offers (item_id, price_gold, price_crystal) values ('leite_manga', 700, null) on conflict (item_id) do update set price_gold = excluded.price_gold, price_crystal = excluded.price_crystal;
insert into public.shop_offers (item_id, price_gold, price_crystal) values ('emerald_egg', null, 500) on conflict (item_id) do update set price_gold = excluded.price_gold, price_crystal = excluded.price_crystal;
-- map_rates: 21
insert into public.map_rates (map_id, rate, gold_base, xp_base, spawn_max_ps) values ('mapinha6', 1, 60, 110, 3) on conflict (map_id) do update set rate = excluded.rate, gold_base = excluded.gold_base, xp_base = excluded.xp_base;
insert into public.map_rates (map_id, rate, gold_base, xp_base, spawn_max_ps) values ('arena', 1, 60, 110, 3) on conflict (map_id) do update set rate = excluded.rate, gold_base = excluded.gold_base, xp_base = excluded.xp_base;
insert into public.map_rates (map_id, rate, gold_base, xp_base, spawn_max_ps) values ('terra', 1.2, 72, 132, 3) on conflict (map_id) do update set rate = excluded.rate, gold_base = excluded.gold_base, xp_base = excluded.xp_base;
insert into public.map_rates (map_id, rate, gold_base, xp_base, spawn_max_ps) values ('mapinha5', 1.8, 108, 198, 3) on conflict (map_id) do update set rate = excluded.rate, gold_base = excluded.gold_base, xp_base = excluded.xp_base;
insert into public.map_rates (map_id, rate, gold_base, xp_base, spawn_max_ps) values ('mapinha7', 1, 60, 110, 3) on conflict (map_id) do update set rate = excluded.rate, gold_base = excluded.gold_base, xp_base = excluded.xp_base;
insert into public.map_rates (map_id, rate, gold_base, xp_base, spawn_max_ps) values ('mapinha8', 1.1, 66, 121, 3) on conflict (map_id) do update set rate = excluded.rate, gold_base = excluded.gold_base, xp_base = excluded.xp_base;
insert into public.map_rates (map_id, rate, gold_base, xp_base, spawn_max_ps) values ('mapinha10', 2.2, 132, 242, 3) on conflict (map_id) do update set rate = excluded.rate, gold_base = excluded.gold_base, xp_base = excluded.xp_base;
insert into public.map_rates (map_id, rate, gold_base, xp_base, spawn_max_ps) values ('mapinha9', 2.2, 132, 242, 3) on conflict (map_id) do update set rate = excluded.rate, gold_base = excluded.gold_base, xp_base = excluded.xp_base;
insert into public.map_rates (map_id, rate, gold_base, xp_base, spawn_max_ps) values ('mapinha11', 2.4, 144, 264, 3) on conflict (map_id) do update set rate = excluded.rate, gold_base = excluded.gold_base, xp_base = excluded.xp_base;
insert into public.map_rates (map_id, rate, gold_base, xp_base, spawn_max_ps) values ('mapinha12', 2.6, 156, 286, 3) on conflict (map_id) do update set rate = excluded.rate, gold_base = excluded.gold_base, xp_base = excluded.xp_base;
insert into public.map_rates (map_id, rate, gold_base, xp_base, spawn_max_ps) values ('mapinha13', 1, 60, 110, 3) on conflict (map_id) do update set rate = excluded.rate, gold_base = excluded.gold_base, xp_base = excluded.xp_base;
insert into public.map_rates (map_id, rate, gold_base, xp_base, spawn_max_ps) values ('cave01', 1, 60, 110, 3) on conflict (map_id) do update set rate = excluded.rate, gold_base = excluded.gold_base, xp_base = excluded.xp_base;
insert into public.map_rates (map_id, rate, gold_base, xp_base, spawn_max_ps) values ('cristal_cave', 1, 60, 110, 3) on conflict (map_id) do update set rate = excluded.rate, gold_base = excluded.gold_base, xp_base = excluded.xp_base;
insert into public.map_rates (map_id, rate, gold_base, xp_base, spawn_max_ps) values ('florest_bone', 1, 60, 110, 3) on conflict (map_id) do update set rate = excluded.rate, gold_base = excluded.gold_base, xp_base = excluded.xp_base;
insert into public.map_rates (map_id, rate, gold_base, xp_base, spawn_max_ps) values ('florest_ice', 1, 60, 110, 3) on conflict (map_id) do update set rate = excluded.rate, gold_base = excluded.gold_base, xp_base = excluded.xp_base;
insert into public.map_rates (map_id, rate, gold_base, xp_base, spawn_max_ps) values ('florest_shiny', 1, 60, 110, 3) on conflict (map_id) do update set rate = excluded.rate, gold_base = excluded.gold_base, xp_base = excluded.xp_base;
insert into public.map_rates (map_id, rate, gold_base, xp_base, spawn_max_ps) values ('ruinas_de_venus', 1, 60, 110, 3) on conflict (map_id) do update set rate = excluded.rate, gold_base = excluded.gold_base, xp_base = excluded.xp_base;
insert into public.map_rates (map_id, rate, gold_base, xp_base, spawn_max_ps) values ('ruinas', 1, 60, 110, 3) on conflict (map_id) do update set rate = excluded.rate, gold_base = excluded.gold_base, xp_base = excluded.xp_base;
insert into public.map_rates (map_id, rate, gold_base, xp_base, spawn_max_ps) values ('valley_plume', 1, 60, 110, 3) on conflict (map_id) do update set rate = excluded.rate, gold_base = excluded.gold_base, xp_base = excluded.xp_base;
insert into public.map_rates (map_id, rate, gold_base, xp_base, spawn_max_ps) values ('revo_rout', 1, 60, 110, 3) on conflict (map_id) do update set rate = excluded.rate, gold_base = excluded.gold_base, xp_base = excluded.xp_base;
insert into public.map_rates (map_id, rate, gold_base, xp_base, spawn_max_ps) values ('cidade_principal', 1, 60, 110, 3) on conflict (map_id) do update set rate = excluded.rate, gold_base = excluded.gold_base, xp_base = excluded.xp_base;
-- hatch_pools emerald: 45
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'grass', 'common', 'caterpie') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'grass', 'common', 'weedle') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'grass', 'common', 'metapod') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'grass', 'common', 'kakuna') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'grass', 'rare', 'butterfree') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'grass', 'rare', 'ivysaur') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'grass', 'rare', 'tangela') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'grass', 'rare', 'gloom') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'grass', 'rare', 'weepinbell') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'grass', 'epic', 'venusaur') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'grass', 'epic', 'victreebel') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'grass', 'epic', 'vileplume') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'fire', 'common', 'charmander') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'fire', 'common', 'vulpix') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'fire', 'common', 'growlithe') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'fire', 'rare', 'charmeleon') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'fire', 'rare', 'magmar') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'fire', 'epic', 'charizard') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'fire', 'epic', 'arcanine') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'fire', 'epic', 'flareon') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'water', 'common', 'squirtle') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'water', 'common', 'poliwag') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'water', 'common', 'psyduck') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'water', 'rare', 'wartortle') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'water', 'epic', 'blastoise') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'water', 'epic', 'vaporeon') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'water', 'epic', 'lapras') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'water', 'epic', 'gyarados') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'electric', 'common', 'pikachu') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'electric', 'common', 'voltorb') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'electric', 'common', 'magnemite') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'electric', 'rare', 'electabuzz') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'electric', 'epic', 'jolteon') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'electric', 'epic', 'raichu') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'electric', 'epic', 'magneton') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'dark', 'common', 'ekans') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'dark', 'common', 'gastly') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'dark', 'common', 'meowth') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'dark', 'rare', 'arbok') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'dark', 'rare', 'haunter') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'dark', 'rare', 'muk') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'dark', 'epic', 'gengar') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'dark', 'epic', 'umbreon') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'dragon', 'epic', 'dragonair') on conflict do nothing;
insert into public.hatch_pools (egg_type, element, tier, species) values ('emerald', 'dragon', 'epic', 'exeggutor_alola') on conflict do nothing;