/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IdleRouteImport } from './routes/idle'
import { Route as HexchampionsRouteImport } from './routes/hexchampions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicPurgeUserRouteImport } from './routes/api/public/purge-user'

const IdleRoute = IdleRouteImport.update({
  id: '/idle',
  path: '/idle',
  getParentRoute: () => rootRouteImport,
} as any)
const HexchampionsRoute = HexchampionsRouteImport.update({
  id: '/hexchampions',
  path: '/hexchampions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPurgeUserRoute = ApiPublicPurgeUserRouteImport.update({
  id: '/api/public/purge-user',
  path: '/api/public/purge-user',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hexchampions': typeof HexchampionsRoute
  '/idle': typeof IdleRoute
  '/api/public/purge-user': typeof ApiPublicPurgeUserRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hexchampions': typeof HexchampionsRoute
  '/idle': typeof IdleRoute
  '/api/public/purge-user': typeof ApiPublicPurgeUserRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hexchampions': typeof HexchampionsRoute
  '/idle': typeof IdleRoute
  '/api/public/purge-user': typeof ApiPublicPurgeUserRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hexchampions' | '/idle' | '/api/public/purge-user'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hexchampions' | '/idle' | '/api/public/purge-user'
  id: '__root__' | '/' | '/hexchampions' | '/idle' | '/api/public/purge-user'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HexchampionsRoute: typeof HexchampionsRoute
  IdleRoute: typeof IdleRoute
  ApiPublicPurgeUserRoute: typeof ApiPublicPurgeUserRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/idle': {
      id: '/idle'
      path: '/idle'
      fullPath: '/idle'
      preLoaderRoute: typeof IdleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hexchampions': {
      id: '/hexchampions'
      path: '/hexchampions'
      fullPath: '/hexchampions'
      preLoaderRoute: typeof HexchampionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/purge-user': {
      id: '/api/public/purge-user'
      path: '/api/public/purge-user'
      fullPath: '/api/public/purge-user'
      preLoaderRoute: typeof ApiPublicPurgeUserRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HexchampionsRoute: HexchampionsRoute,
  IdleRoute: IdleRoute,
  ApiPublicPurgeUserRoute: ApiPublicPurgeUserRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
