// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import { getEvent } from 'vinxi/http';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

/**
 * Pega as variáveis de ambiente de forma segura no runtime do Worker.
 * No Cloudflare Worker com TanStack Start (Nitro), as chaves estão em event.context.cloudflare.env.
 */
function getRuntimeEnv(): Record<string, string | undefined> {
  const env: Record<string, any> = {};

  // 1. Tentar contexto do Vinxi/H3 (Edge Runtime)
  try {
    const event = getEvent();
    const cfEnv = (event?.context as any)?.cloudflare?.env;
    if (cfEnv) {
      Object.assign(env, cfEnv);
    }
  } catch (e) {
    // getEvent pode falhar se chamado fora de um ciclo de request
  }

  // 2. Tentar process.env (Node/Bun/Preview)
  try {
    if (typeof process !== 'undefined' && process.env) {
      Object.assign(env, process.env);
    }
  } catch (e) {}

  // 3. Fallback para globalThis (último recurso, desencorajado)
  const g = globalThis as any;
  if (g.ADMIN_SB_KEY) env.ADMIN_SB_KEY = g.ADMIN_SB_KEY;
  if (g.SUPABASE_URL) env.SUPABASE_URL = g.SUPABASE_URL;
  if (g.SUPABASE_SERVICE_ROLE_KEY) env.SUPABASE_SERVICE_ROLE_KEY = g.SUPABASE_SERVICE_ROLE_KEY;

  return env;
}

function createSupabaseAdminClient() {
  const env = getRuntimeEnv();
  
  const SUPABASE_URL = env.SUPABASE_URL || env.VITE_SUPABASE_URL || "https://kgrspvqhpgiuxvkcxgcp.supabase.co";
  const ADMIN_SB_KEY = env.ADMIN_SB_KEY || env.SUPABASE_SERVICE_ROLE_KEY;
  const SUPABASE_SERVICE_ROLE_KEY = env.SUPABASE_SERVICE_ROLE_KEY || ADMIN_SB_KEY;

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [];
    if (!SUPABASE_URL) missing.push('SUPABASE_URL');
    if (!SUPABASE_SERVICE_ROLE_KEY) missing.push('ADMIN_SB_KEY/SERVICE_ROLE');
    
    throw new Error(`Erro de Configuração no Servidor: ${missing.join(', ')} ausente no runtime do Worker. Verifique as Secrets no painel Lovable.`);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_SERVICE_ROLE_KEY),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

// SECURITY: O cliente é instanciado dentro do Proxy para garantir que getRuntimeEnv() 
// seja chamado no momento do acesso (dentro de uma Server Function), onde o contexto do request está disponível.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    const client = createSupabaseAdminClient();
    return Reflect.get(client, prop, receiver);
  },
});
